name: Deploy App to GH-Pages

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ ci ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Install Packages
      run: npm install
    - name: Build Project
      run: npm run build
    # - name: Build & Deploy
    #   run: |
    #     git config --global user.email ${{ secrets.DEPLOY_EMAIL }}
    #     git config --global user.name ${{ secrets.DEPLOY_NAME }}
    #     git remote set-url origin https://${{ secrets.DEPLOY_TOKEN }}@github.com/anlai/wled-designer.git
    #     npm run deploy
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
